databases:
  - name: sacco-db
    databaseName: kms_sacco
    user: kms_sacco_user
    region: oregon

services:
  - type: web
    name: sacco-backend
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn sacco_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        fromDatabase:
          name: sacco-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,portalkmscom.vercel.app,www.kmssacco.co.ke"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: "kms2022.sacco@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "cimi zklx qdhx gfcn"
      - key: DEFAULT_FROM_EMAIL
        value: "kms2022.sacco@gmail.com"
      - key: SACCO_NAME
        value: "KMS SACCO"
      - key: SACCO_SHARE_VALUE
        value: "5000.00"
      - key: SACCO_MIN_CONTRIBUTION
        value: "1000.00"
      - key: SACCO_LOAN_INTEREST_RATE
        value: "12.00"
    region: oregon