databases:
  - name: sacco-db
    databaseName: sacco_db
    user: sacco_user
    region: oregon

services:
  - type: web
    name: sacco-backend
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn sacco_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        fromDatabase:
          name: sacco-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
    region: oregon