# Generated by Django 5.2 on 2025-04-12 07:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('reminder_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='SCHEDULED', max_length=10)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('successful_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='MemberContributionSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('BIANNUAL', 'Bi-Annual'), ('ANNUAL', 'Annual'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custom_months', models.CharField(blank=True, max_length=50)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Contribution Schedule',
                'verbose_name_plural': 'Member Contribution Schedules',
            },
        ),
        migrations.CreateModel(
            name='ContributionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('quarter', models.PositiveIntegerField(blank=True, null=True)),
                ('report_date', models.DateField()),
                ('total_members', models.PositiveIntegerField(default=0)),
                ('contributing_members', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previous_period_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('growth_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='contribution_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_contribution_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-quarter'],
                'unique_together': {('year', 'month'), ('year', 'quarter')},
            },
        ),
    ]
