# Generated by Django 5.2 on 2025-04-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaccoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_value', models.DecimalField(decimal_places=2, default=100.0, help_text='Value of a single share', max_digits=10)),
                ('minimum_monthly_contribution', models.DecimalField(decimal_places=2, default=1000.0, help_text='Minimum required monthly contribution', max_digits=10)),
                ('loan_interest_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Annual interest rate for loans (%)', max_digits=5)),
                ('maximum_loan_multiplier', models.DecimalField(decimal_places=2, default=3.0, help_text='Maximum loan amount as a multiple of shares', max_digits=5)),
                ('loan_processing_fee_percentage', models.DecimalField(decimal_places=2, default=1.0, help_text='Loan processing fee as percentage of loan amount', max_digits=5)),
                ('loan_insurance_percentage', models.DecimalField(decimal_places=2, default=1.0, help_text='Loan insurance fee as percentage of loan amount', max_digits=5)),
                ('phone_number', models.CharField(default='+254700000000', help_text='SACCO contact phone number', max_length=20)),
                ('email', models.EmailField(default='info@sacco.com', help_text='SACCO contact email', max_length=254)),
                ('postal_address', models.CharField(default='P.O. Box 12345, Nairobi', help_text='SACCO postal address', max_length=100)),
                ('physical_address', models.CharField(default='Nairobi, Kenya', help_text='SACCO physical address', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SACCO Setting',
                'verbose_name_plural': 'SACCO Settings',
            },
        ),
    ]
