# Generated by Django 5.2 on 2025-04-12 07:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_share_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_loans', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_at_hand', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fees_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('operational_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dividend_payments', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active_members', models.PositiveIntegerField(default=0)),
                ('total_members', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Summary',
                'verbose_name_plural': 'Financial Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DividendDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distribution_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(default='Interest Income', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_dividends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-distribution_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('REJECTED', 'Rejected'), ('SETTLED', 'Settled'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=10)),
                ('purpose', models.TextField()),
                ('term_months', models.PositiveIntegerField(default=12)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expected_repayment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('disbursed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateField()),
                ('reference_number', models.CharField(max_length=50)),
                ('transaction_code', models.CharField(max_length=50)),
                ('transaction_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_repayments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='sacco_core.loan')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberShareSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_share_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('share_capital_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('share_capital_completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_year_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previous_year_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentage_of_total_pool', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('number_of_shares', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_dividends_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_dividend_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_dividend_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Share Summary',
                'verbose_name_plural': 'Member Share Summaries',
            },
        ),
        migrations.CreateModel(
            name='SaccoSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='SACCO Organization', max_length=255)),
                ('share_value', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('minimum_monthly_contribution', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('loan_interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('maximum_loan_multiplier', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('loan_processing_fee_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('loan_insurance_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('postal_address', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SACCO Settings',
                'verbose_name_plural': 'SACCO Settings',
            },
        ),
        migrations.CreateModel(
            name='ShareCapital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateField()),
                ('reference_number', models.CharField(max_length=50)),
                ('transaction_code', models.CharField(max_length=50)),
                ('transaction_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_share_capital', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_capital', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('SHARE_CAPITAL', 'Share Capital Payment'), ('MONTHLY_CONTRIBUTION', 'Monthly Contribution'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('DIVIDEND_PAYMENT', 'Dividend Payment'), ('EXPENSE', 'SACCO Expense'), ('INCOME', 'SACCO Income'), ('OTHER', 'Other Transaction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateField()),
                ('transaction_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('related_dividend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='sacco_core.dividenddistribution')),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='sacco_core.loan')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberDividend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_dividends', to='sacco_core.dividenddistribution')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-distribution__distribution_date', '-created_at'],
                'unique_together': {('distribution', 'member')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateField()),
                ('reference_number', models.CharField(max_length=50)),
                ('transaction_code', models.CharField(max_length=50)),
                ('transaction_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_contributions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
                'unique_together': {('member', 'year', 'month')},
            },
        ),
    ]
