# Generated by Django 5.2.1 on 2025-06-09 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_core', '0002_auto_20250609_1647'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycontribution',
            name='contribution_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Monthly Contribution'), ('ADDITIONAL', 'Additional Contribution'), ('CATCHUP', 'Catch-up Payment'), ('PENALTY', 'Penalty Payment'), ('OTHER', 'Other')], default='REGULAR', help_text='Type of contribution', max_length=50),
        ),
        migrations.AddIndex(
            model_name='monthlycontribution',
            index=models.Index(fields=['member', 'year', 'month'], name='sacco_core__member__fdbf7a_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycontribution',
            index=models.Index(fields=['transaction_date'], name='sacco_core__transac_ad9acf_idx'),
        ),
    ]
